<?php
// Defense token
session_start();
$_SESSION['csrf_token'] = md5(uniqid(mt_rand(), true));

// Simulating a login cookie, assuming user has logged in to set this cookie
if (isset($_GET["name"])) {
    $name = $_GET["name"];
    setcookie("login", $name, [
        'expires' => time() + 86400,
        'path' => '/',
        'domain' => 'host.com',
        'secure' => false,
        'httponly' => true,
        'samesite' => 'Lax',
    ]);
    echo "Cookie set ! : login=$name";
} else {
    echo "No Cookie set !";
}
?>
<html>
<head>
    <title>CSRF</title>
</head>
<body>
<script>
    function call() {
        // add csrf defense token
        const url = `simple.php?csrf_token=<?php echo $_SESSION["csrf_token"] ?>`;
        const params = {
            method: 'GET',
            credentials: 'include',
        };

        fetch(url, params)
            .then(response => {
                return response.text();
            })
            .then(data => {
                document.getElementById("answer-div").innerText = data;
            })
            .catch(err => {
                console.log(err);
            });
    }
</script>
<font size="5">
    This page was generated by the Server
    <button onclick="call()">Call the Server</button>
</font>
<div id=answer-div>Waiting for an answer...</div>
<iframe id="iframe" src="../mycode/iframe_infected.php"></iframe>
</body>
</html>